import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = process.env.GOOGLE_GEMINI_API_KEY;

if (!apiKey) {
  throw new Error("Missing GOOGLE_GEMINI_API_KEY environment variable");
}

const genAI = new GoogleGenerativeAI(apiKey);

interface GenerateMarketingImageParams {
  prompt: string;
  restaurantName: string;
  language: "ar" | "en";
  aspectRatio?: "1:1" | "16:9" | "4:3";
}

interface GenerateMarketingImageResult {
  imageBase64: string;
  mimeType: string;
  description: string;
}

/**
 * Generate a marketing image using Gemini's image generation capabilities.
 * Uses gemini-2.5-flash-image-preview (Nano Banana) with
 * responseModalities: ["Text", "Image"]. The 3.1 preview model has a
 * per-project free-tier quota of 0 and reliably 429s on unpaid keys, so
 * we deliberately use the 2.5 preview which is broadly available.
 */
export async function generateMarketingImage(
  params: GenerateMarketingImageParams
): Promise<GenerateMarketingImageResult> {
  const { prompt, restaurantName, language, aspectRatio = "16:9" } = params;

  const model = genAI.getGenerativeModel({
    model: "gemini-2.5-flash-image-preview",
    generationConfig: {
      responseModalities: ["Text", "Image"],
    } as any, // responseModalities not in older SDK types
  });

  const languageLabel = language === "ar" ? "Arabic" : "English";

  const fullPrompt = [
    "Create a professional marketing image for a WhatsApp campaign.",
    `Restaurant: ${restaurantName}`,
    prompt,
    "",
    "Requirements:",
    "- Eye-catching, suitable for mobile viewing",
    "- Clean, professional design",
    `- If text is needed, use ${languageLabel}`,
    "- Optimized for WhatsApp message header",
    `- Aspect ratio: ${aspectRatio}`,
    "- High contrast, bold colors",
    "- Food/restaurant themed if applicable",
    "- No watermarks or placeholder text",
  ].join("\n");

  const response = await model.generateContent(fullPrompt);

  const parts = response.response.candidates?.[0]?.content?.parts || [];

  let imageBase64 = "";
  let mimeType = "image/png";
  let description = "";

  for (const part of parts) {
    if ("text" in part && part.text) {
      description = part.text;
    } else if ("inlineData" in part && part.inlineData) {
      imageBase64 = part.inlineData.data;
      mimeType = part.inlineData.mimeType;
    }
  }

  if (!imageBase64) {
    throw new Error("No image generated by Gemini");
  }

  return { imageBase64, mimeType, description };
}
